branch-defaults:
  default:
    environment: sgaa-prod-docker
    group_suffix: null
global:
  application_name: sgaa-prod-docker
  branch: null
  default_ec2_keyname: sgaa-prod-docker-ssh-keypair
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
