name: Deploy Steps

on:
  push:
    branches: [ feature/elastic-beanstalk ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::417268992578:role/custom-github-actions-role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: ./Backend/SGAA.Api/Dockerfile
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: SGAA
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push --all-tags $REGISTRY/$REPOSITORY

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Init EB CLI
        working-directory: ./infra/deploy
        run: |
          eb init

      - name: Deploy to Elastic Beanstalk
        working-directory: ./infra/deploy
        run: |
          eb deploy
